name: Docker Image
on: 
  push:
    tags:
      - '**'
    branches:
      - master
  pull_request:
    paths: 
      - .github/workflows/jaeger-dockerimage.yml
      - Dockerfile
      - protoc-wrapper
          
jobs:
  build:
    runs-on: ubuntu-latest
    # 24 hours
    timeout-minutes: 1440
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build the Docker image
      run: docker buildx build -t build --load .
    
    # TODO: https://github.com/jaegertracing/docker-protobuf/issues/30
    - name: Test docker image
      run : |
        echo "Please add tests here"

    - name: Push the Docker image
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      run: |
        function build_and_push {
          docker buildx build -t "${{ secrets.DOCKER_USERNAME }}/protobuf:${1}" --platform linux/amd64,linux/arm64/v8 --push .
        }

        if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
        build_and_push "latest"
        elif [[ "${GITHUB_REF}" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            TAG="${GITHUB_REF#"refs/tags/v"}"
            build_and_push "${TAG}"
            build_and_push "latest"
        else
          build_and_push "${GITHUB_REF#"refs/tags/"}"
        fi
